#!/bin/sh
export CROSS_COMPILE=mipsel-linux-gnu-
export NM=${CROSS_COMPILE}nm
export OBJCOPY=${CROSS_COMPILE}objcopy

# build the kernel
make ARCH=mips usr
(cd initramfs && bash mkinitramfs.sh)
make ARCH=mips
$OBJCOPY -O binary --remove-section=.reginfo --remove-section=.mdebug --remove-section=.comment --remove-section=.note --remove-section=.pdr --remove-section=.options --remove-section=.MIPS.options vmlinux vmlinux.bin

# create U-Boot image
rm -f vmlinux.bin.gz 
gzip -9 vmlinux.bin
mkimage -A mips -O linux -T kernel -C gzip -a 0x80060000 -e 0x$($NM vmlinux | grep kernel_entry | cut -f1 -d ' ') -n 'Pollinux PNX8950 TriMemory' -d vmlinux.bin.gz uImage
